### ISSUE TITLE
[Bug]: Tensorflow examples don't work with tensorflow 2.X

### ISSUE THREAD

**Issue by m-janyell0w** [wandb/examples#320]
### Tell us what happened?

Hey there, 
I tried running the examples `tf-cnn-fashion` and `tf-estimator-mnist` using Tensorflow version 2.9.1.

For the former when running train.py I get:
**modulenotfounderror: No module named 'tensorflow.examples'**
and
**attributeerror: module 'tensorflow' has no attribute 'app'**

I think this is because 
1) tensorflow.examples is deprecated in tf v 2.X and 
2) the examples are written for tensorflow versions < 2.X.

Following the [tf docs for migrating code](https://www.tensorflow.org/guide/migrate/upgrade) could fix part of the problem, but the first error remains.

Could you update the examples-code for tf versions >=2.0 or give me further instructions how I can get them to work with tf v 2.9.1?

Best, Micha

**Comment by tcapelle** [comment]
Thanks for flagging this out, they are indeed pretty old. We will update them. In the meantime, the colabs should be up to date.
